name: BuildBattleAI
version: '${project.version}'
main: ru.ashesha.buildBattleAI.BuildBattleAI
authors: [ McAshesha ]
description: A competitive mini-game on building and explaining the buildings of AI
